-- Keep /api/notes and any existing records during the transition.
CREATE TABLE IF NOT EXISTS note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE note ALTER COLUMN content TYPE TEXT;
